import React, { useState, useRef } from 'react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { ArrowLeftRight, FileCode, FileDown, Eye, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import html2pdf from 'html2pdf.js';

const HtmlToPdf = () => {
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [pageSize, setPageSize] = useState('a4');
  const [orientation, setOrientation] = useState('portrait');
  const [margin, setMargin] = useState('10');
  const previewRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  const handleGeneratePdf = async () => {
    if (!input.trim()) {
      toast({
        variant: "destructive",
        title: "Input required",
        description: "Please enter some HTML to convert.",
      });
      return;
    }

    setIsGenerating(true);

    try {
      // Create a temporary container for the HTML
      const container = document.createElement('div');
      container.innerHTML = input;
      container.style.padding = '20px';
      container.style.fontFamily = 'Arial, sans-serif';
      document.body.appendChild(container);

      const marginValue = parseInt(margin);

      const options = {
        margin: marginValue,
        filename: 'converted-document.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          letterRendering: true,
        },
        jsPDF: {
          unit: 'mm',
          format: pageSize,
          orientation: orientation as 'portrait' | 'landscape'
        }
      };

      await html2pdf().set(options).from(container).save();

      // Clean up
      document.body.removeChild(container);

      toast({
        title: "PDF generated successfully",
        description: "Your PDF has been downloaded.",
      });
    } catch (error) {
      if (error instanceof Error) {
        toast({
          variant: "destructive",
          title: "Generation failed",
          description: error.message,
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const sampleHtml = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 20px; }
    .highlight { background-color: #fef3c7; padding: 2px 6px; border-radius: 4px; }
    ul { margin-left: 20px; }
    .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f3f4f6; }
  </style>
</head>
<body>
  <h1>Sample Document</h1>
  <p>This is a <span class="highlight">sample HTML document</span> that demonstrates the HTML to PDF conversion feature.</p>

  <h2>Features</h2>
  <ul>
    <li>Supports custom styling</li>
    <li>Handles tables and lists</li>
    <li>Preserves formatting</li>
    <li>Multiple page sizes available</li>
  </ul>

  <h2>Sample Table</h2>
  <table>
    <tr>
      <th>Feature</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>Text formatting</td>
      <td>Supported</td>
    </tr>
    <tr>
      <td>Images</td>
      <td>Supported</td>
    </tr>
    <tr>
      <td>CSS Styles</td>
      <td>Supported</td>
    </tr>
  </table>

  <div class="footer">
    Generated by Sleek Utility Hub - HTML to PDF Converter
  </div>
</body>
</html>`;

  const handleLoadSample = () => {
    setInput(sampleHtml);
    toast({
      title: "Sample loaded",
      description: "Sample HTML has been loaded into the input.",
    });
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-1 container py-8">
        <div className="mb-8">
          <a href="/" className="text-primary hover:underline flex items-center gap-1 text-sm mb-4">
            <ArrowLeftRight className="h-4 w-4" />
            Back to all tools
          </a>
          <h1 className="text-3xl font-bold mb-2">HTML to PDF Converter</h1>
          <p className="text-muted-foreground">Convert HTML content to a downloadable PDF document.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileCode className="h-5 w-5" />
                  Input HTML
                </CardTitle>
                <CardDescription>
                  Paste your HTML code here (including styles)
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  className="min-h-[300px] font-mono text-sm"
                  placeholder="<html>
<body>
  <h1>Your HTML here...</h1>
</body>
</html>"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                />
                <div className="flex justify-between mt-4">
                  <Button variant="outline" onClick={handleLoadSample}>
                    Load Sample
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>PDF Options</CardTitle>
                <CardDescription>
                  Configure the output PDF settings
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="pageSize">Page Size</Label>
                    <Select value={pageSize} onValueChange={setPageSize}>
                      <SelectTrigger id="pageSize">
                        <SelectValue placeholder="Select page size" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="a4">A4</SelectItem>
                        <SelectItem value="letter">Letter</SelectItem>
                        <SelectItem value="legal">Legal</SelectItem>
                        <SelectItem value="a3">A3</SelectItem>
                        <SelectItem value="a5">A5</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="orientation">Orientation</Label>
                    <Select value={orientation} onValueChange={setOrientation}>
                      <SelectTrigger id="orientation">
                        <SelectValue placeholder="Select orientation" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="portrait">Portrait</SelectItem>
                        <SelectItem value="landscape">Landscape</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="margin">Margin (mm)</Label>
                  <Select value={margin} onValueChange={setMargin}>
                    <SelectTrigger id="margin">
                      <SelectValue placeholder="Select margin" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="0">None (0mm)</SelectItem>
                      <SelectItem value="5">Small (5mm)</SelectItem>
                      <SelectItem value="10">Medium (10mm)</SelectItem>
                      <SelectItem value="15">Large (15mm)</SelectItem>
                      <SelectItem value="20">Extra Large (20mm)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <Button
                  onClick={handleGeneratePdf}
                  className="w-full"
                  disabled={isGenerating || !input.trim()}
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating PDF...
                    </>
                  ) : (
                    <>
                      <FileDown className="h-4 w-4 mr-2" />
                      Generate & Download PDF
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Eye className="h-5 w-5" />
                Preview
              </CardTitle>
              <CardDescription>
                Live preview of your HTML content
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div
                ref={previewRef}
                className="min-h-[400px] border rounded-lg p-4 bg-white overflow-auto"
                style={{ maxHeight: '500px' }}
              >
                {input ? (
                  <div dangerouslySetInnerHTML={{ __html: input }} />
                ) : (
                  <div className="flex items-center justify-center h-full text-muted-foreground">
                    <p>Enter HTML to see preview</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Tips for Best Results</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm text-muted-foreground">
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">1.</span>
                Include inline styles or &lt;style&gt; tags for custom formatting
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">2.</span>
                Use web-safe fonts for consistent rendering
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">3.</span>
                Images should use absolute URLs or base64 encoding
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">4.</span>
                Complex CSS (flexbox, grid) may have limited support
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">5.</span>
                Test with the preview before generating the PDF
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary font-bold">6.</span>
                All conversion happens in your browser - no data is sent to any server
              </li>
            </ul>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  );
};

export default HtmlToPdf;
